# AntiMobBuild Configuration

############################################
#                                          #
#            ___     __  ___ ____          #
#           /   |   /  |/  // __ )         #
#          / /| |  / /|_/ // __  |         #
#         / ___ | / /  / // /_/ /          #
#        /_/  |_|/_/  /_//_____/           #
#                                          #
#            AntiMobBuild                  #
#                                          #
############################################

# Set to 'true' to enable broadcasting messages to players
# when mob spawns are canceled by the plugin.
# Set to 'false' to disable broadcasting messages to players.
broadcastMessagesToPlayer: false

# Set to 'true' to enable broadcasting messages to the console
# when mob spawns are canceled by the plugin.
# Set to 'false' to disable broadcasting messages to the console.
broadcastMessagesToConsole: false

# You can configure the entities that can be spawned here

# Set to 'true' to allow the creation of Iron Golems.
# Set to 'false' to prevent the creation of Iron Golems.
canCreateIronGolem: false

# Set to 'true' to allow the creation of Snow Golems.
# Set to 'false' to prevent the creation of Snow Golems.
canCreateSnowMan: false

# Set to 'true' to allow the creation of Wither Bosses.
# Set to 'false' to prevent the creation of Wither Bosses.
canCreateWither: false

# Set to 'true' to allow the curing of infected Villagers.
# Set to 'false' to prevent the curing of infected Villagers.
canCureVillager: false

# Set to 'true' to allow Villagers to be infected by zombies.
# Set to 'false' to prevent Villagers from being infected.
canInfectVillager: false

# Set to 'true' to allow Silverfish to spawn from blocks.
# Set to 'false' to prevent Silverfish from spawning.
canSpawnSilverFishOnBlocks: false

# Set to 'true' to allow the transformation of Zombies into Drowned.
# Set to 'false' to prevent Zombies from transforming.
canTransformZombieInDrowned: false

# Set to 'true' to allow mobs to spawn from eggs.
# Set to 'false' to prevent mobs from spawning from eggs.
canSpawnFromEggs: false
