# AntiMobBuild Configuration

############################################
#                                          #
#            ___     __  ___ ____          #
#           /   |   /  |/  // __ )         #
#          / /| |  / /|_/ // __  |         #
#         / ___ | / /  / // /_/ /          #
#        /_/  |_|/_/  /_//_____/           #
#                                          #
#            AntiMobBuild                  #
#                                          #
############################################

# Set to 'true' to enable broadcasting messages to players
# when mob spawns are canceled by the plugin.
# Set to 'false' to disable broadcasting messages to players.
broadcast-messages-to-player: true

# Set to 'true' to enable broadcasting messages to the console
# when mob spawns are canceled by the plugin.
# Set to 'false' to disable broadcasting messages to the console.
broadcast-messages-to-console: true

# You can configure the entities that can be spawned here

# Set to 'true' to allow the creation of Iron Golems.
# Set to 'false' to prevent the creation of Iron Golems.
can-create-irongolem: false

# Set to 'true' to allow the creation of Snow Golems.
# Set to 'false' to prevent the creation of Snow Golems.
can-create-snowman: false

# Set to 'true' to allow the creation of Wither Bosses.
# Set to 'false' to prevent the creation of Wither Bosses.
can-create-wither: false

# Set to 'true' to allow the curing of infected Villagers.
# Set to 'false' to prevent the curing of infected Villagers.
can-cure-villager: false

# Set to 'true' to allow Villagers to be infected by zombies.
# Set to 'false' to prevent Villagers from being infected.
can-infect-villager: false

# Set to 'true' to allow Silverfish to spawn from blocks.
# Set to 'false' to prevent Silverfish from spawning.
can-spawn-silver-fish-on-blocks: false

# Set to 'true' to allow mobs to spawn from eggs.
# Set to 'false' to prevent mobs from spawning from eggs.
can-spawn-from-eggs:
  enabled: true
  exceptions:
    - WOLF
# prevent mobs from spawning natural on the server
natural-mob-spawn:
  enabled: true # set to true to enable natural mob spawning
  exceptions: # add exceptions , if you set WOLF as exceptions and natural-mob-spawn.enabled is true , only wolf can spawn
    - WOLF
    - ZOMBIE
    - CREEPER
