name: AntiMobBuild
version: '2.0-test'
main: org.example.test.antimobbuild.AntiMobBuild
api-version: 1.16
author: Mardssss
commands:
  amb:
    description: Reloads the configuration
    usage: /amb reload
    permission: antimobbuild.reload
    aliases: [antimobbuild]
    tab-completions:
      - reload
permissions:
  antimobbuild.reload:
    description: Permission to reload the configuration
    default: op